In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neural_network import MLPClassifier 
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt

In [2]:
from functions import generateDfFromMongoDB

In [3]:
host = "mongodb://localhost"
port = 27017
db = "20221114"
collection = "sensordata"
query = {}
resultsLimit = 80000

df = generateDfFromMongoDB(host, collection, port, db, resultsLimit)

In [4]:
df.head()

,_id,Sensor address,sensor_id,humidity,temperature,vdd,waterleak,time,outside temperature (TF),outside relativeHumidity (TF),precipitation (TF),precipitation type (TF),light,motion
0,63728011caf3517df237c199,Matsal Addiva Sigurdsgatan,eui-a81758fffe075c91,36,21.9,3624,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
1,63728011caf3517df237c19a,Pingisrum Addiva Sigurdsgatan,eui-a81758fffe075b65,37,22.2,3629,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
2,637280a2caf3517df237c19b,Skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b66,36,22.3,3633,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
3,637280a2caf3517df237c19c,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.9,3636,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
4,6372848c679d686ec9534093,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.8,3636,0.0,"2022/11/14, 19:10:20",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN

In [5]:
df = df.drop(columns="_id")
df.head()

,Sensor address,sensor_id,humidity,temperature,vdd,waterleak,time,outside temperature (TF),outside relativeHumidity (TF),precipitation (TF),precipitation type (TF),light,motion
0,Matsal Addiva Sigurdsgatan,eui-a81758fffe075c91,36,21.9,3624,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
1,Pingisrum Addiva Sigurdsgatan,eui-a81758fffe075b65,37,22.2,3629,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
2,Skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b66,36,22.3,3633,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
3,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.9,3636,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
4,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.8,3636,0.0,"2022/11/14, 19:10:20",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN

In [6]:
df.dtypes

Sensor address                    object
sensor_id                         object
humidity                           int64
temperature                      float64
vdd                                int64
waterleak                        float64
time                              object
outside temperature (TF)         float64
outside relativeHumidity (TF)    float64
precipitation (TF)                object
precipitation type (TF)           object
light                            float64
motion                           float64
dtype: object

In [7]:
df.head()

,Sensor address,sensor_id,humidity,temperature,vdd,waterleak,time,outside temperature (TF),outside relativeHumidity (TF),precipitation (TF),precipitation type (TF),light,motion
0,Matsal Addiva Sigurdsgatan,eui-a81758fffe075c91,36,21.9,3624,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
1,Pingisrum Addiva Sigurdsgatan,eui-a81758fffe075b65,37,22.2,3629,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
2,Skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b66,36,22.3,3633,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
3,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.9,3636,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
4,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.8,3636,0.0,"2022/11/14, 19:10:20",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN

In [8]:
     
le = LabelEncoder()
le.fit(df["sensor_id"])
df["sensor_id"] = le.transform(df["sensor_id"])
le.fit(df["Sensor address"])
df["Sensor address"] = le.transform(df["Sensor address"])
le.fit(df["time"])
df["time"] = le.transform(df["time"])
le.fit(df["precipitation type (TF)"])
df["precipitation type (TF)"] = le.transform(df["precipitation type (TF)"])



df = df.drop(columns="light")
df = df.drop(columns="motion")
df = df.drop(columns="Sensor address")
df = df.drop(columns="precipitation (TF)")
df = df.drop(columns="vdd")

df = df.dropna()
df.head()

,sensor_id,humidity,temperature,waterleak,time,outside temperature (TF),outside relativeHumidity (TF),precipitation type (TF)
0,4,36,21.9,0.0,0,6.8,98.7,0
1,1,37,22.2,0.0,0,6.8,98.7,0
2,2,36,22.3,0.0,1,6.8,98.7,0
3,3,29,25.9,0.0,1,6.8,98.7,0
4,3,29,25.8,0.0,2,6.8,98.7,0

In [9]:
df.dtypes

sensor_id                          int32
humidity                           int64
temperature                      float64
waterleak                        float64
time                               int32
outside temperature (TF)         float64
outside relativeHumidity (TF)    float64
precipitation type (TF)            int32
dtype: object

In [10]:
df_X = df.drop(columns="temperature")
df_y = df["temperature"]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size=0.25, random_state=42)

In [12]:
import time

In [13]:
start4 = time.time()
clf4  = MLPClassifier(random_state=42,learning_rate_init=0.0001,hidden_layer_sizes=(100,100,100,100,100,100,100,100,100,100))
clf4.fit(X_train, y_train)
y_predict_clf4  = clf4.predict(X_test)
end4 = time.time()
print('Time taken for clf4 program: ', end4 - start4)

ValueError: Unknown label type: (array([21.5, 21.7, 21.1, ..., 21.5, 21.5, 22.1]),)